[package]
name = "async_await"
version = "0.1.0"
edition = "2024"

[dependencies]
error-chain = "0.12.4"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
tokio = { version = "1.48.0", features = ["full"] }
